FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
# Install necessary packages
RUN apt-get update
RUN apt-get install -y python-opencv \
                    python-pip \
                    libopencv-dev \
                    libcanberra-gtk3-module \
                    vim-tiny \
                    mosquitto-clients
# Install paho mqtt to send messages to broker
RUN pip install paho-mqtt
RUN mkdir hw3
COPY . /hw3
WORKDIR /hw3
ENTRYPOINT [ "python" ]
CMD [ "hw3.py" ]
